- name: install consul
  hosts: all
  roles:
    - consul-install

- name: bootstrap consul
  hosts: consul-server
  roles:
    - consul-bootstrap

- name: add more consul server
  hosts: consul-agent1
  roles:
    - consul-add-server

- name: add consul clients
  hosts: consul-agent2
  roles:
    - consul-add-client

- name: configure consul systemd service on all node
  hosts: all
  roles:
    - consul-systemd

- name: start consul cluster
  hosts: all
  tasks:
    - name: start consul servers
      systemd:
        name: consul
        state: restarted
        enabled: yes
        daemon_reload: yes
      become: yes