- name: Check if Swarm is Already Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  become: yes
  tags: swarm

- name: Add Managers to the Swarm
  shell: "docker swarm join --token {{ hostvars['swarm-manager']['manager_token']['stdout'] }} {{ hostvars['swarm-manager'].ansible_host }}:2377"
  when: swarm_status.rc != 0
  become: yes
  tags: swarm