- name: initialize docker swarm
  hosts: swarm-manager
  roles:
    - swarm-init

- name: add manager to the swarm
  hosts: swarm-managers
  roles:
    - swarm-add-manager

- name: add workers to the swarm
  hosts: swarm-workers
  roles:
    - swarm-add-worker